#!/bin/bash
source scripts/modules.sh $1

# get linux distro
DISTRO=$(awk '/DISTRIB_ID=/' /etc/*-release | sed 's/DISTRIB_ID=//' | tr '[:upper:]' '[:lower:]')

if [[ "$DISTRO" == "arch" ]]; then
    # refresh arch keyring
    pacman --noconfirm -Sy archlinux-keyring >/dev/null 2>&1
    # install aur helper
    sudo -u "$1" git -C "/tmp" clone --depth 1 --single-branch --no-tags -q "https://aur.archlinux.org/$AURHELPER.git" "/tmp/$AURHELPER" ||
	{
	    cd "/tmp/$AURHELPER" || return 1
	    sudo -u "$1" git pull --force origin master
	}
	cd "/tmp/$AURHELPER" || exit 1
	sudo -u "$1" -D "/tmp/$AURHELPER" makepkg --noconfirm -si >/dev/null 2>&1 || return 1
fi

# install base packs
base=(sudo sed curl stow unzip)
pkginstall root ${base[@]} || "Error: could not install UTILS packages."

# create user
adduser() {
    read -p "Insert user name: " username
    if id "$username" &>/dev/null; then
        echo $username
    else
        adduser $username wheel || "Error: could not add user."
        addsudo $username || "Error: could not add user to sudoers."
        echo $username
    fi
}
username=$( adduser ) || "Error!"

# allow sudo without pass
sed -i '/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^#//g' /etc/sudoers

# create basic folders and get dotfiles
sudo -u $username mkdir  /home/$username/docs  /home/$username/devs  /home/$username/repos  /home/$username/ws
sudo -u $username git clone https://github.com/nash169/dotfiles.git /home/$username/devs/dotfiles

# setup shell
shell=(zsh)
pkginstall $1 ${shell[@]} || "Error: could not install ZSH packages."
cd /home/$1/devs/dotfiles && sudo -u $1 stow zsh -t /home/$1/
chsh -s /bin/zsh "$1" >/dev/null 2>&1

# setup ssh
ssh=(openssh)
pkginstall $1 ${ssh[@]} || "Error: could not install SSH packages."
read -p "Insert your email: " email
sudo -u $1 ssh-keygen -t ed25519 -C "$email"

# tiling window manager
DWM="/home/bernardo/devs/st"
git clone git@github.com:nash169/st-tmp.git $DWM 
git -C $DWM remote add upstream git://git.suckless.org/dwm 
git -C $DWM fetch upstream
git -C $DWM merge upstream/master
git -C $DWM checkout custom
git -C $DWM rebase upstream/master

configuredesktop $username || "Error!"

# terminal
ST="/home/bernardo/devs/st"
git clone git@github.com:nash169/st-tmp.git $ST 
git -C $ST remote add upstream git://git.suckless.org/st 
git -C $ST fetch upstream
git -C $ST merge upstream/master
git -C $ST checkout custom
git -C $ST rebase upstream/master

terminal=(tmux exa bat)
pkginstall $1 ${terminal[@]} || "Error: could not install TERMINAL packages."

configureterminal $username || "Error!"


tex=(
    texlive-bin
    texlive-fontsrecomended
    texlive-latexextra
    texlive-latexrecomended
    texlive-latex
    texlive-basic
    texlive-xetex
    texlive-mathscience
    texlive-fontsextra
    texlive-langenglish
    texlive-context
    texlive-luatex
    texlive-plaingeneric
    texlive-binextra
    texlive-bibtexextra
    texlive-pictures
    texlive-langfrench
    texlive-langgerman
    texlive-fontutils
    )

# # EDITOR
# source /root/linux-config/scripts/modules/editor.sh $1 $username

# # DEVELOP
# source /root/linux-config/scripts/modules/develop.sh $1 $username

# # EXPLORER
# source /root/linux-config/scripts/modules/explorer.sh $1 $username

# # BROWSER
# source /root/linux-config/scripts/modules/browser.sh $1 $username

# # MULTIMEDIA
# source /root/linux-config/scripts/modules/media.sh $1 $username

# # READER
# source /root/linux-config/scripts/modules/reader.sh $1 $username

# # EMAIL
# source /root/linux-config/scripts/modules/email.sh $1 $username

# # SOUND
# source /root/linux-config/scripts/modules/sound.sh $1 $username

# # BLUETOOTH
# source /root/linux-config/scripts/modules/bluetooth.sh $1 $username

# # DOWNLOAD
# source /root/linux-config/scripts/modules/download.sh $1 $username

#
sed -i '/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^/#/g' /etc/sudoers

# #  Node support
# pkginstall nodejs npm
# sudo npm install -g neovim

# # Python support
# pkginstall python-pip
# pip install pynvim --user

# pkginstall ripgrep fzf lf

# # Allow to draw image in terminal
# pkginstall python-ueberzug-git

# # Don't know yet
# pkginstall neovim-remote
#  install -g tree-sitter-cli

# install tiling window manager
# DWM="/home/bernardo/devs/dwm"
# git clone git@github.com:nash169/dwm-tmp.git $DWM 
# git -C $DWM remote add upstream git://git.suckless.org/dwm 
# git -C $DWM fetch upstream
# git -C $DWM merge upstream/master


