#!/bin/sh

# changing "ls" to "exa"
alias ls='eza -al --color=always --group-directories-first' # my preferred listing
alias la='eza -a --color=always --group-directories-first'  # all files and dirs
alias ll='eza -l --color=always --group-directories-first'  # long format
alias lt='eza -aT --color=always --group-directories-first' # tree listing

# fuzzy finder shortcuts
alias pf="pacman -Slq | fzf -m --preview 'cat <(pacman -Si {1}) <(pacman -Fl {1} | awk \"{print \$2}\")' | xargs -ro sudo pacman -S"
alias yf="yay -Slq | fzf -m --preview 'cat <(yay -Si {1}) <(yay -Fl {1} | awk \"{print \$2}\")' | xargs -ro  yay -S"
# alias fp="find "$(pwd)" | fzf | xclip -selection clipboard"
alias fp="fd | fzf | xargs realpath | xclip -selection clipboard"

# lf
alias lf='lfrun'

# neovim
alias v='nvim'

# reload zsh
alias rz='source $HOME/.zshenv && source ${ZDOTDIR:-$HOME}/.zshrc'

# additional aliases
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi
