user_pref("extensions.zotero.dataDir", "$HOME/zotero");
user_pref("extensions.zotero.groups.copyAnnotations", false);
user_pref("extensions.zotero.groups.copyChildFileAttachments", false);
user_pref("extensions.zotero.groups.copyChildLinks", false);
user_pref("extensions.zotero.sync.storage.groups.enabled", false);
user_pref("extensions.zotero.attachmentRenameTemplate", "{{ creators editors max=\"1\" case=\"lower\" suffix=\"_\" replaceFrom=\"\\s+\" replaceTo=\"_\" regexOpts=\"g\" }}{{ year suffix=\"_\" }}{{ title truncate=\"100\" case=\"lower\"  replaceFrom=\"\\s+\" replaceTo=\"_\" regexOpts=\"g\"}}");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower+\"_\"+shorttitle(1,0).lower+\"_\"+year");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower+\"_\"+shorttitle(1,0).lower+\"_\"+year");
user_pref("extensions.zotero.reader.contentDarkMode", false);
user_pref("browser.theme.toolbar-theme", 0);
